apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaseci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaseci
  template:
    metadata:
      labels:
        app: jaseci
    spec:
      containers:
        - name: jaseci
          image: jaseci
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: "mongodb://mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017/?replicaSet=rs0"
            - name: REDIS_HOST
              value: "redis://redis:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: jaseci
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: jaseci